### ISSUE TITLE
Лев Толстой в родительном падеже - ОШИБКА

### ISSUE THREAD

**Issue by electroae4** [petrovich/pytrovich#4]
Лев Толстой в родительном падеже (GENITIVE) почему-то преобразуется в Лева Толстого, а не в Льва Толстого.
На демонстрационном сайте (petrovich.nlpub.ru) исходной библиотеки результат правильный.

**Comment by alexeyev** [comment]
Добрый день, спасибо за интерес к проекту. Да, проблема есть, правда, на демо-сайте она, кажется, тоже воспроизводится.
![изображение](https://user-images.githubusercontent.com/1089594/221184729-4a9e57a2-4a33-4a23-a269-d3181aa5b776.png)

**Comment by electroae4** [comment]
Добрый день. Вы имя "Лев" написали на место фамилии. Там в форме указано, что сначала надо написать фамилию, затем имя. Поэтому у вас имя неправильно просклонялось.
![Clear_form](https://user-images.githubusercontent.com/109409726/221351939-7b143530-65ea-4aed-b30b-ff02828b10ab.png)

Если в форму написать Толстой Лев, то всё ОК.
![Form_with_data](https://user-images.githubusercontent.com/109409726/221352045-2f4d5f36-bab2-446f-8027-aab2c88720c2.png)

**Comment by alexeyev** [comment]
Спасибо огромное. Нехорошая была ошибка.
