### ISSUE TITLE
Bug with genitive case

### ISSUE THREAD

**Issue by vavilon1205** [petrovich/pytrovich#5]
Имя Никита не склоняет в родительном падеже.

**Comment by alexeyev** [comment]
Добрый вечер. Приведите пример, пожалуйста.

У меня вот такой скрипт
```python
print(pytrovich.__version__)
maker = PetrovichDeclinationMaker()
print(maker.make(NamePart.FIRSTNAME, Gender.MALE, Case.GENITIVE, "Никита")) 
```

приводит к такому выводу:
```
0.0.4
Никиты
```

**Comment by vavilon1205** [comment]
p = Petrovich()

lname ='Иванов'
fname ='Никита'
mname ='Сергеевич'

cased_lastname = p.lastname(lname, Case.GENITIVE, Gender.MALE)
cased_firstname = p.firstname(fname, Case.GENITIVE, Gender.MALE)
cased_middlename = p.middlename(mname, Case.GENITIVE, Gender.MALE)
cased_last_first_middle = f"{cased_lastname} {cased_firstname} {cased_middlename}"

print(cased_last_first_middle)

**Comment by vavilon1205** [comment]
Добрый вечер.

**Comment by alexeyev** [comment]
Здравствуйте. Такого объекта в `pytrovich` нет.

Похоже, используете другую библиотеку, рекомендую создать issue при соответствующем репозитории: https://github.com/damirazo/Petrovich/issues

Удачи.

**Comment by vavilon1205** [comment]
Извиняюсь! Перешел на Вашу библиотеку. Она намного лучше, чем pytrovich!!!!!
